### ISSUE TITLE
Terraform script ( API Lambda & Crawler Lambda)

### ISSUE THREAD

**Issue by LyndonP** [ActoKids/devops#2]
- Communicate with the Crawler team and API team
- Figure out access to create a full Lambda function for the crawler script
- Watch tutorials on how to implement the scripts using a terraform script

Estimated time: 10 hours

**Comment by jams2018** [comment]
Watched tutorials on terraform script. Since it's a brand new subject to me, it has been taking longer than expected.

Following steps on
https://learn.hashicorp.com/terraform/getting-started/build
https://seanmcgary.com/posts/how-to-deploy-an-aws-lambda-with-terraform/

I am prioritizing this task and the crawler script has been worked on. The API lambda may not be completed unless the crawler script is automated. 

Waiting for an approval to create a Lambda function

Implemented a .tf file to each team on GitHub

**Comment by jams2018** [comment]
Following steps on 
https://learn.hashicorp.com/terraform/getting-started/build

**Comment by jams2018** [comment]
I am prioritizing this task and the crawler script has been worked on. The API lambda may not be completed unless the crawler script is automated.

**Comment by jams2018** [comment]
- Time estimated: 10h
- Time spent: 10h
- PR link: 
https://github.com/ActoKids/devops/blob/dev/scripts/lambdaterraform/lambdaapi.tf
https://github.com/ActoKids/devops/blob/dev/scripts/lambdaterraform/lambdacrawler.tf
https://github.com/ActoKids/devops/blob/dev/scripts/lambdaterraform/variables.tf
- Wiki link: https://github.com/ActoKids/devops/tree/dev/scripts/lambdaterraform/readme.txt

**Comment by jams2018** [comment]
![test_functions](https://user-images.githubusercontent.com/38123178/52386424-f21d7f80-2a3a-11e9-811a-a1267014a592.PNG)

**Comment by toddysm** [comment]
Few things:
- Don't commit to DEV directly :)
- We need to get the TF scripts to create environments and not simple components - we can discuss offline
- Do you have this tested from somebody else? Did you test somebody else's implementation?

**Comment by jams2018** [comment]
Toddy, sorry for the confusion.
I submitted a new pull request after the class and it addresses both the Sprint 2 (Terraform on Lambda) and Sprint 4 (Terraform on Lambda with Parameters) On #24, the peers are still reviewing the code. I'll address it tomorrow in class.

Time Estimated: 10 hours
Actual Time: 13 hours
PR: https://github.com/ActoKids/devops/pull/24
Wiki: https://github.com/ActoKids/devops/tree/dev/scripts/lambdaterraform/readme.txt
