### ISSUE TITLE
Travis CI for UI (prod)

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#47]
Final task is to make sure the prod Travis Ci pipeline for webui is configured correctly and deploying properly the website into the s3 prod bucket. 

Actual time: 3 hr
Estimated time: 3 hr

**Comment by dashinay** [comment]
Looking into webui travis Ci yaml scipt I have noticed that it was deploying correctly though files weren't the correct ones to be deployed. Working on Sprint 4 with Erick I wasn't able to set up hosted website on s3 bucket as it was missing index file. It was due to the fact that UI is done with react and it needed to be build before being deployed. Previous Travis Ci pipeline was configured to deploy everything on UI repository.

 - I have solved the issue by reconfiguring the Travis Ci to run build for react app and deploy the produced build artifact(website files with index file)  into the prod s3 bucket. 
- Current configuration of Travis Ci production pipeline is set up correctly and have no issues.

PR: https://github.com/ActoKids/web-ui/pull/35
https://github.com/ActoKids/web-ui/pull/54 (dev merge into prod)
Build: https://travis-ci.org/ActoKids/web-ui/builds/505886444
Wiki: https://github.com/ActoKids/web-ui/wiki/Travis-CI
Bug: https://github.com/ActoKids/devops/issues/42
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/113
https://github.com/ActoKids/devops/issues/57
https://github.com/ActoKids/devops/issues/61

Provided reviews:
I have reviewed Shota's PR and provided a feedback with specific issues he was having and requested changes on them.
I have checked the changes on Api team for travis ci deployment and had approved after testing it.

Reviews I received:
Betelhem and Erick have reviewed the changes into the yaml file and both gave feedback of it saying there were no issues with the script and had provided approval of the [PR](https://github.com/ActoKids/web-ui/pull/35). PR has been successfully merged.

**Comment by dashinay** [comment]
Deployment into the production environment 
![ui_prod_deployment](https://user-images.githubusercontent.com/34629972/54706075-4e27f900-4afb-11e9-93ae-031bfa99a2b2.png)

**Comment by LyndonP** [comment]
Verified the .travis.yml does build and push to prod.
