### ISSUE TITLE
Crawler dashboard for PROD

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#49]

**Comment by LyndonP** [comment]
## Sprint 5 Tasks
Automate Crawler dashboard for PROD
Task Description:
•	Use Terraform to create a CloudWatch dashboard after the Lambda function has been instantiated in AWS
#SOURCES:
[Link 1](https://dev.to/frosnerd/monitoring-aws-lambda-functions-with-cloudwatch-1nap)
[Link 2](https://stephenmann.io/post/setting-up-monitoring-and-alerting-on-amazon-aws-with-terraform)
[Link 3](https://medium.com/coryodaniel/til-the-cloudwatch-dashboard-api-is-a-pita-to-use-with-terraform-23ef6bc30c0)

### To complete this task, I used the references above. The tricky part here is that the CloudWatch instantiation HAS to happen AFTER the Lambda function instantiation. This is mainly because the Logs would have nothing to read from and error out.
Estimated Hours:
4 Hours
Actual Hours:
5 Hours

The Dashboard will look similar to this:

![CW](https://user-images.githubusercontent.com/34604046/54170290-5a44f400-4433-11e9-94e2-1858aa97dfe3.jpg)


[Pull Request](https://github.com/ActoKids/devops/pull/56)
